# Generated by Django 3.1.3 on 2020-11-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='products',
        ),
        migrations.AddField(
            model_name='shops',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.product'),
            preserve_default=False,
        ),
    ]
