# Generated by Django 3.1.3 on 2020-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_auto_20201115_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='products',
        ),
        migrations.AddField(
            model_name='shops',
            name='products',
            field=models.ManyToManyField(to='ecommerceApp.Product'),
        ),
    ]
