# Generated by Django 3.1.3 on 2020-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_auto_20201115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_products', to='ecommerceApp.Product'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='products',
            field=models.ManyToManyField(related_name='shop_products', to='ecommerceApp.Product'),
        ),
    ]
