# Generated by Django 3.1.3 on 2020-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_auto_20201121_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='country_code',
            field=models.CharField(default='JO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='ecommerceApp.Product'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='products',
            field=models.ManyToManyField(related_name='products', to='ecommerceApp.Product'),
        ),
    ]
